### ISSUE TITLE
Sonarr V4 not supported?

### ISSUE THREAD

**Issue by PutzJimmy** [RandomNinjaAtk/docker-sonarr-extended#11] opened 2022-12-08 10:26 UTC
Hi. Trying to set this up as I love your Lidarr extended one. But noticed that this one pulls the new v4 sonarr and don't seem to be able to fully run the AutoConfig and Recyclarr or is there any extra config that has to be done?

Also does this support a dual setup, I currently have two sonarr setups to have one up to 1080p and one 2160p.

**Comment by RandomNinjaAtk** [comment] 2022-12-08 11:31
Recyclarr is working, that was fixed in the latest update as of yesterday. However, I haven't re-tested the AutoConfig since the move to V4, so that may be broken.

I believe sonarr itself doesn't support multiple qualities/versions, so you'd have to continue to run two setups, which you could do with this container.

**Comment by PutzJimmy** [comment] 2022-12-08 11:38
Gotcha. thx for the quick reply and keep up the awesome work =)

**Comment by RandomNinjaAtk** [comment] 2022-12-08 11:45
> Gotcha. thx for the quick reply and keep up the awesome work =)

One thing to note, recylcarr was upgraded to V3, so you likely need to rebuild your config file to support it... The included default config files were updated to support the changes, see here:
https://github.com/RandomNinjaAtk/docker-sonarr-extended/blob/main/root/recyclarr.yaml

**Comment by PutzJimmy** [comment] 2022-12-08 12:00
Yeh i did a clean install on the side of my other sonarr just for testing but nothing was imported from AutoConfig nor Recyclarr

**Comment by RandomNinjaAtk** [comment] 2022-12-08 12:03
Double check your `/config/extended/configs/recyclarr.yaml` to make sure its configured with URL and API key. (https://github.com/RandomNinjaAtk/docker-sonarr-extended/wiki/Recyclarr.bash)

I'll probably setup a test instance soon to bugfix and verify things do what there supposed to do on a new install.

**Comment by PutzJimmy** [comment] 2022-12-08 12:14
It was not configured with url and api, putting that in made recyclarr work. Can you post what should go into the naming?

**Comment by PutzJimmy** [comment] 2022-12-08 12:27
Did a test now with just keeping the config.xml and sonarr.db to keep the authentication settings. recyclarr.yaml did not update with url and api

**Comment by PutzJimmy** [comment] 2022-12-08 12:44
Did a fresh one again with latest and now it seems to be working =) thx a bunch

**Comment by RandomNinjaAtk** [comment] 2022-12-08 12:44
I have confirmed everything is working as intended. So it should be working as designed on a fresh install with the latest update.

**Comment by RandomNinjaAtk** [comment] 2022-12-08 12:46
Thanks for the bug report

**Closed** 2022-12-08 12:45 UTC
Labels: bug, good first issue
